services:
  nginx:
    container_name: nginx1
    image: nginx:latest
    ports:
      - "7200:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - python

  python:
    container_name: python1
    build:
      context: .
      dockerfile: dockerfile

  
